### ISSUE TITLE
DPAttachments JQuery error

### ISSUE THREAD

**Issue by denvarel** [Digital-Peak/DPAttachments#10]
Attachments do not get deleted using delete button.
Standard Joomla 3.9.1 on CloudAccess cloud (free joomla hosting server)
DPAttachments 2.2.0 
In frontend: the "delete" button throw the message 
"Success
1 attachment trashed."
 but after refresh the page is unchanged. The attachment is in its place... A new refresh shows the same thing.

Even more: in component's backend: DPAttachments Manager: Attachments selecting the attachments (one or more) and pressing "Trash" returns an "Message
0 attachments trashed." and nothing happends.
The side menu does do othing, the unpublish joomla button does not unpublish...

Basically, the only way of trashing an attachment is to edit it and change its status from editing interface.

And drag and drop functionality seems stuck at 100% It does not suppose to refresh the page as the "delete" does? The attachment get uploaded but the interface does not allow another upload since is busy showing the upload bar.

The firebug console says there is an error:
TypeError: e is null[Learn More] core.js:1:2790
removeMessages 
http://unicserv.joomla.com/media/system/js/core.js?66f82dc137b8fa777b5436b6551cfe5c:1 
renderMessages http://unicserv.joomla.com/media/system/js/core.js?66f82dc137b8fa777b5436b6551cfe5c:1 success http://unicserv.joomla.com/joomla/category-blog/5-what-is-a-category-blog.html:88 
c4jQuery

**Comment by laoneo** [comment]
This is a break in joomla 3.9.1 from https://github.com/joomla/joomla-cms/pull/22851.

**Comment by laoneo** [comment]
Fixed with https://github.com/Digital-Peak/DPAttachments/commit/197b872a6f9d1c8e03dbe6f192df71924b63e47f
