### ISSUE TITLE
The DPCases\HTML\Block\Icon message in frontend at pressing "edit" 

### ISSUE THREAD

**Issue by denvarel** [Digital-Peak/DPAttachments#11]
Updated 3,0,0 version of DPAttachments
Pressing "Edit:" an existing attachment in front end result in the following error:

0
Class 'DPCases\HTML\Block\Icon' not found
The page you requested cannot be found.

**Comment by laoneo** [comment]
Is fixed with https://github.com/Digital-Peak/DPAttachments/commit/483ce9b3df0e6d20d5fe7c895f7625411e964902. Thanks for reporting.
