### ISSUE TITLE
My extension is not discovered

### ISSUE THREAD

**Issue by astridx** [Digital-Peak/DPAttachments#12]
The problem is definitely my lack of docker knowledge.

I spent some time with dpdocker today and am enthusiastic about webserver. 

For Build I would like to keep my previous tools. So I want to symlink from my project directory to the webserver container. But: It does not work. I see the linked directory, but I can not enter it. And a discover did not find it. 

I also asked a question in stackoverflow:
https://joomla.stackexchange.com/questions/28531/dpdocker-and-joomla

It is not a dpdocker problem. So it's OK if you close the issue. But I'm still trying here. Maybe you have a tip

**Comment by laoneo** [comment]
You need to create the symlinks from within the container. I guess you did from your host computer.

**Comment by astridx** [comment]
Oops, that was wrong. I actually wanted to open the issue in the DPdocker Repo. Anyway, thanks for the answer.
