### ISSUE TITLE
DPAttachment is not pulling in DPCalendar Attachments/Images using Exchange Sync/Import

### ISSUE THREAD

**Issue by newburns** [Digital-Peak/DPAttachments#5]
DPCalendar Exchange sync does not show any attached images, pdf's, or files.
DPAttachment is installed and published.
Server Settings
` Database Version 	5.6.22-log `
`Database Collation 	latin1_swedish_ci `
` PHP Version 	5.5.20 `
` Web Server 	Apache/2.2.15 (CentOS) `
` WebServer to PHP Interface 	apache2handler `
` Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT `
` Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT `
` User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0  `

**Comment by laoneo** [comment]
This is more of a DPCalendar issue than DPAttachments as DPAttachments only supports local attachments on your Joomla site.
