### ISSUE TITLE
DPAttachments causes warning in another component's details view

### ISSUE THREAD

**Issue by jaanusnurmoja** [Digital-Peak/DPAttachments#6]
When DPA is turned on then JoomlaEventManager (JEM) event details view shows a warning:
Table Event not supported. File not found.
See
https://github.com/jemproject/JEM-3/issues/258

May come from somewhere here:
https://github.com/Digital-Peak/DPAttachments/search?utf8=%E2%9C%93&q=JTable%3A%3AgetInstance&type=Code

**Comment by laoneo** [comment]
I can't reproduce the issue. I've installed JEM, loaded the sample data and installed DPAttachments. Created a calendar menu link and opened an event. I'm using the version 2.1.3. How can I reproduce the issue?

**Comment by jaanusnurmoja** [comment]
I am using JEM version 3.0.7

**Comment by laoneo** [comment]
Where can I download version 3?

**Comment by jaanusnurmoja** [comment]
In their Github
https://github.com/jemproject/JEM-3
Download the master as zip and upload & install via Joomla installer

**Comment by jaanusnurmoja** [comment]
`if ($context == 'com_jem.event') 
{ 
      return false; 
 }`
this code in plugins/content/dpattachments/dpattachments.php removes this warning. 
Tested it, see
https://github.com/jemproject/JEM-3/issues/258#issuecomment-96160876

**Comment by laoneo** [comment]
In Joomla there is a convention that the table name should be event and not events as it is in JEM-3. But it is unlikely that the JEM team will change the name of the table. In commit 450b6e6d6d1e4db1f16de82a371ac2d201f7b3fe I've added an additional check, if the table doesn't exist. This will be shipped with the next minor version too.

**Comment by jaanusnurmoja** [comment]
Thanks :)
