### ISSUE TITLE
why filename can not be numbers?

### ISSUE THREAD

**Issue by baijianpeng** [Digital-Peak/DPAttachments#8]
If I upload a file which has a filename consists of pure numbers, like: 538493.jpg , this name will be changed by DPAttachments to -.jpg .

Why numbers can not be used as filename?

If you think there should be some alphabet in the filename, why not allow user to define a default pre-text, like "file", then this pure-number-filename will be changed to file-538493.jpg.

**Comment by laoneo** [comment]
In the file administrator/components/com_dpattachments/models/attachment.php change line 102 to 

    preg_replace("/[^\p{L}|0-9]+/u", "-", substr($fileName, 0, strlen($fileName) - strlen($uploadedFileExtension) - 1)) . '.' .

does it fix the issue?
