### ISSUE TITLE
use the original filename as attachment title?

### ISSUE THREAD

**Issue by baijianpeng** [Digital-Peak/DPAttachments#9]
I noticed that DPAttachments will use the filename (without extension) as the attachment title, however, this feature is not good enough: if the original filename contains non-ASCII characters, or just pure-number filename, the title will be generated differently instead of using the original filename.

I think, in any way, the original filename should be used as the attachment title , of course, allows to be overrided by editing the attachment at backend DPAttachments manager.

Since there is no option to edit/input the attachment title when adding it at frontend, you should allow to use the original filename as the title. In this way, I can name my file a good filename, then upload it, though the filename will be changed for storing in file system, the "attachment title" will be the same as my original filename, which is in my control.

Thank you.

**Comment by laoneo** [comment]
You can edit an attachment after upload, so it makes sense at it is for now.
